create table ACCOUNT (
  ACCOUNT_ID bigint IDENTITY not null,
  CREATE_TIME TIMESTAMP DEFAULT NOW(),
  BALANCE DECIMAL(16,2),
  primary key (ACCOUNT_ID)
);

create table PAYMENT (
  PAYMENT_ID bigint IDENTITY not null,
  CREATE_TIME TIMESTAMP DEFAULT NOW(),
  AMOUNT DECIMAL(16,2),
  LEFT_ACCOUNT_ID bigint not null,
  RIGHT_ACCOUNT_ID bigint not null,
  primary key (PAYMENT_ID)
);

ALTER TABLE PAYMENT
ADD FOREIGN KEY (LEFT_ACCOUNT_ID)
REFERENCES ACCOUNT(ACCOUNT_ID);

ALTER TABLE PAYMENT
ADD FOREIGN KEY (RIGHT_ACCOUNT_ID)
REFERENCES ACCOUNT(ACCOUNT_ID);

ALTER TABLE PAYMENT
ADD CONSTRAINT PMNT_AMNT
CHECK  (AMOUNT > 0);

ALTER TABLE ACCOUNT
ADD CONSTRAINT ACCNT_BLNC
CHECK  (BALANCE >= 0);

ALTER TABLE PAYMENT
ADD CHECK (LEFT_ACCOUNT_ID <> RIGHT_ACCOUNT_ID);
